const MAIN_SCREEN_APP_BAR_TITLE="Discover";
const MAIN_SCREEN_BEST_POPULAR_MOVIES_AND_SERIALS=
    "BEST POPULAR MOVIES AND SERIALS";
const MAIN_SCREEN_SEE_MORE="See More";
const MAIN_SCREEN_CHECK_MOVIE_SHOWTIMES="Check Movie\nShowtimes";
const SHOW_CASES_TITLE="SHOW CASES";
const SHOW_CASES_SEE_MORE="MORE CASES";
const BEST_ACTORS_TITLE="BEST ACTORS";
const BEST_ACTORS_SEE_MORE="MORE ACTORS";

const MOVIE_DETAILS_SCREEN_ACTORS_TITLE="ACTORS";
const MOVIE_DETAILS_SCREEN_CREATORS_TITLE="CREATORS";
const MOVIE_DETAILS_SCREEN_CREATORS_SEE_MORE="MORE CREATORS";
const MOVIE_DETAILS_STORYLINE_TITLE="STORYLINE";
const PLAY_TRAILER_BUTTON_TEXT="PLAY TRAILER";
const RATE_MOVIE_BUTTON_TEXT="RATE MOVIE";